"""
Property-based tests for client-side validation.

This module tests that client-side validation detects invalid input formats
and displays appropriate validation error messages in real-time for each
notification channel type (EMAIL, SMS, WHATSAPP).

**Validates: Requirements 6.2, 6.4**

Property 12: Client-Side Validation
- For any invalid input in channel-specific validation fields (email format, phone formats),
  the React application SHALL display appropriate real-time validation error messages.
"""

import pytest
from hypothesis import given, settings, Verbosity, HealthCheck
from playwright.sync_api import Page
from tests.utils.generators import invalid_emails, invalid_sms_numbers, invalid_whatsapp_numbers


class TestClientSideValidation:
    """Test suite for verifying client-side validation displays appropriate error messages."""
    
    @given(invalid_email=invalid_emails())
    @settings(
        max_examples=25,
        verbosity=Verbosity.quiet,
        suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
        deadline=None
    )
    @pytest.mark.property_test
    def test_email_validation_shows_error_for_invalid_format(self, page: Page, notification_page, invalid_email):
        """Property test: Invalid email formats display validation error in real-time.
        
        **Validates: Requirements 6.2, 6.4**
        
        For any invalid email format:
        1. Navigate to the application
        2. Select EMAIL notification type
        3. Fill recipient field with invalid email
        4. Trigger blur event on the field
        5. Wait for validation to process (200-300ms)
        6. Verify validation error message is visible
        
        Invalid email examples generated:
        - Missing @ symbol
        - Multiple @ symbols
        - No local part
        - No domain
        - Spaces in address
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            invalid_email: Invalid email format generated by Hypothesis
        """
        # Navigate to the application
        notification_page.navigate()
        
        # Select EMAIL notification type
        notification_page.select_type('EMAIL')
        
        # Fill recipient field with invalid email
        recipient_input = page.locator('[data-testid="recipient"]')
        recipient_input.fill(invalid_email)
        
        # Trigger blur event to initiate validation
        recipient_input.blur()
        
        # Wait for validation to process (as per spec: 200-300ms)
        page.wait_for_timeout(250)
        
        # Verify that the error message is visible
        error_locator = page.locator('[data-testid="recipient-error"]')
        is_error_visible = error_locator.is_visible()
        
        assert is_error_visible, \
            f"Email validation error should be visible for invalid email format. " \
            f"Invalid email: '{invalid_email}'"
    
    @given(invalid_sms=invalid_sms_numbers())
    @settings(
        max_examples=25,
        verbosity=Verbosity.quiet,
        suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
        deadline=None
    )
    @pytest.mark.property_test
    def test_sms_validation_shows_error_for_invalid_format(self, page: Page, notification_page, invalid_sms):
        """Property test: Invalid SMS phone formats display validation error in real-time.
        
        **Validates: Requirements 6.2, 6.4**
        
        For any invalid ES region SMS phone number format:
        1. Navigate to the application
        2. Select SMS notification type
        3. Fill recipient field with invalid phone number
        4. Trigger blur event on the field
        5. Wait for validation to process (200-300ms)
        6. Verify validation error message is visible
        
        Invalid SMS number examples generated:
        - Missing +34 prefix
        - Wrong country code (not Spain)
        - Starting with 8 or 9 (not 6 or 7 for mobile)
        - Wrong length (too short)
        - Contains letters or special characters
        
        Valid ES SMS format: +34 followed by 9 digits starting with 6 or 7
        Examples: +34612345678, +34712345678
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            invalid_sms: Invalid SMS phone number generated by Hypothesis
        """
        # Navigate to the application
        notification_page.navigate()
        
        # Select SMS notification type
        notification_page.select_type('SMS')
        
        # Fill recipient field with invalid phone number
        recipient_input = page.locator('[data-testid="recipient"]')
        recipient_input.fill(invalid_sms)
        
        # Trigger blur event to initiate validation
        recipient_input.blur()
        
        # Wait for validation to process (as per spec: 200-300ms)
        page.wait_for_timeout(250)
        
        # Verify that the error message is visible
        error_locator = page.locator('[data-testid="recipient-error"]')
        is_error_visible = error_locator.is_visible()
        
        assert is_error_visible, \
            f"SMS validation error should be visible for invalid phone format. " \
            f"Invalid SMS number: '{invalid_sms}' (must be +34 + 9 digits starting with 6 or 7)"
    
    @given(invalid_whatsapp=invalid_whatsapp_numbers())
    @settings(
        max_examples=25,
        verbosity=Verbosity.quiet,
        suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
        deadline=None
    )
    @pytest.mark.property_test
    def test_whatsapp_validation_shows_error_for_invalid_format(self, page: Page, notification_page, invalid_whatsapp):
        """Property test: Invalid WhatsApp E.164 formats display validation error in real-time.
        
        **Validates: Requirements 6.2, 6.4**
        
        For any invalid E.164 format phone number:
        1. Navigate to the application
        2. Select WHATSAPP notification type
        3. Fill recipient field with invalid phone number
        4. Trigger blur event on the field
        5. Wait for validation to process (200-300ms)
        6. Verify validation error message is visible
        
        Invalid E.164 examples generated:
        - Missing + prefix
        - Too short (< 7 digits total)
        - Too long (> 15 digits total)
        - Contains letters or special characters
        - Spaces in number
        
        Valid E.164 format: + followed by 7-15 digits
        Examples: +34612345678 (Spain), +12025551234 (USA), +442071838750 (UK)
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            invalid_whatsapp: Invalid E.164 phone number generated by Hypothesis
        """
        # Navigate to the application
        notification_page.navigate()
        
        # Select WHATSAPP notification type
        notification_page.select_type('WHATSAPP')
        
        # Fill recipient field with invalid phone number
        recipient_input = page.locator('[data-testid="recipient"]')
        recipient_input.fill(invalid_whatsapp)
        
        # Trigger blur event to initiate validation
        recipient_input.blur()
        
        # Wait for validation to process (as per spec: 200-300ms)
        page.wait_for_timeout(250)
        
        # Verify that the error message is visible
        error_locator = page.locator('[data-testid="recipient-error"]')
        is_error_visible = error_locator.is_visible()
        
        assert is_error_visible, \
            f"WhatsApp validation error should be visible for invalid E.164 format. " \
            f"Invalid WhatsApp number: '{invalid_whatsapp}' (must be + followed by 7-15 digits)"
