"""
Property-based tests for form submission triggering API requests.

This module tests that form submissions correctly trigger HTTP POST requests
to the backend notification API with all required fields in the correct format.

**Validates: Requirements 2.2, 3.1, 6.3**

Property 1: Form Submission Triggers API Request
- For any valid notification data (type, recipient, message, and optional subject),
  when the user submits the form, the React application SHALL trigger a POST request
  to the backend API with all required fields in the correct format.
"""

import pytest
import json
from hypothesis import given, settings, Verbosity, HealthCheck
from playwright.sync_api import Page
from tests.utils.generators import valid_notifications


class TestFormSubmissionAPI:
    """Test suite for verifying form submission triggers API requests."""
    
    @given(notification_data=valid_notifications())
    @settings(max_examples=25, verbosity=Verbosity.quiet, suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow], deadline=None)
    @pytest.mark.property_test
    def test_form_submission_triggers_api_request(self, page: Page, notification_page, notification_data):
        """Property test: Form submission triggers API POST request with correct data.
        
        **Validates: Requirements 2.2, 3.1, 6.3**
        
        For any valid notification data generated by Hypothesis:
        1. Navigate to the application
        2. Fill the form with the generated notification data
        3. Intercept network requests to capture the POST to /api/v1/notifications
        4. Submit the form
        5. Verify the POST request was sent with:
           - Correct endpoint: http://localhost:8081/api/v1/notifications
           - Correct HTTP method: POST
           - Correct Content-Type: application/json
           - Request body containing all required fields with correct values
           - No authentication headers present
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            notification_data: Valid notification data from Hypothesis generator
                {
                    'type': 'EMAIL'|'SMS'|'WHATSAPP',
                    'recipient': str,
                    'message': str,
                    'subject': str (only for EMAIL)
                }
        """
        # List to capture intercepted requests
        intercepted_requests = []
        
        def handle_route(route):
            """Intercept and capture API requests, then continue."""
            if '/api/v1/notifications' in route.request.url:
                intercepted_requests.append({
                    'url': route.request.url,
                    'method': route.request.method,
                    'headers': dict(route.request.headers),
                    'body': route.request.post_data_json if route.request.method == 'POST' else None
                })
            
            # Mock a successful response
            route.abort()  # Abort to avoid real backend call in test
        
        # Navigate to the application
        notification_page.navigate()
        
        # Set up route handler to intercept requests
        page.route('**/api/v1/notifications', handle_route)
        
        # Fill the form with notification data
        notification_type = notification_data['type']
        recipient = notification_data['recipient']
        message = notification_data['message']
        subject = notification_data.get('subject')
        
        notification_page.fill_form(notification_type, recipient, message, subject)
        
        # Submit the form
        notification_page.submit()
        
        # Verify a request was intercepted
        assert len(intercepted_requests) > 0, \
            f"Expected at least one POST request to /api/v1/notifications, but got none. " \
            f"Notification data: type={notification_type}, recipient={recipient}, message={message}"
        
        # Get the first request (should be the form submission)
        request_data = intercepted_requests[0]
        
        # Assertion 1: Verify correct endpoint
        assert '/api/v1/notifications' in request_data['url'], \
            f"Request URL should contain /api/v1/notifications, got: {request_data['url']}"
        
        # Assertion 2: Verify correct HTTP method
        assert request_data['method'] == 'POST', \
            f"Request method should be POST, got: {request_data['method']}"
        
        # Assertion 3: Verify Content-Type header is application/json
        content_type = request_data['headers'].get('content-type', '').lower()
        assert 'application/json' in content_type or content_type == 'application/json', \
            f"Content-Type header should be application/json, got: {request_data['headers'].get('content-type')}"
        
        # Assertion 4: Verify request body contains required fields
        request_body = request_data['body']
        assert request_body is not None, \
            f"Request body should not be None"
        
        assert isinstance(request_body, dict), \
            f"Request body should be a JSON object, got: {type(request_body)}"
        
        # Verify type field matches
        assert 'type' in request_body, \
            f"Request body should contain 'type' field. Got: {request_body}"
        assert request_body['type'] == notification_type, \
            f"Request body type should be {notification_type}, got: {request_body['type']}"
        
        # Verify recipient field matches
        assert 'recipient' in request_body, \
            f"Request body should contain 'recipient' field. Got: {request_body}"
        assert request_body['recipient'] == recipient, \
            f"Request body recipient should be {recipient}, got: {request_body['recipient']}"
        
        # Verify message field matches
        assert 'message' in request_body, \
            f"Request body should contain 'message' field. Got: {request_body}"
        assert request_body['message'] == message, \
            f"Request body message should be {message}, got: {request_body['message']}"
        
        # Verify subject field for EMAIL notifications
        if notification_type == 'EMAIL':
            # For EMAIL, subject should be included only if it's non-empty/non-whitespace
            if subject and subject.strip():  # Only check if subject is non-empty
                assert 'subject' in request_body, \
                    f"Request body should contain 'subject' field for EMAIL type with non-empty subject. Got: {request_body}"
                assert request_body['subject'] == subject, \
                    f"Request body subject should be {subject}, got: {request_body['subject']}"
            else:
                # Empty or whitespace-only subject may or may not be included (frontend's choice)
                pass
        else:
            # For SMS and WHATSAPP, subject should NOT be included
            assert 'subject' not in request_body, \
                f"Request body should NOT contain 'subject' field for {notification_type} type. Got: {request_body}"
        
        # Assertion 5: Verify no authentication headers are present
        # Check for common authentication header names
        auth_headers = ['authorization', 'auth', 'x-auth-token', 'x-api-key', 'cookie', 'x-csrf-token']
        for auth_header in auth_headers:
            assert auth_header not in [h.lower() for h in request_data['headers'].keys()], \
                f"Request should not contain authentication header '{auth_header}'. " \
                f"Got headers: {request_data['headers']}"
    
    @given(notification_data=valid_notifications())
    @settings(max_examples=25, verbosity=Verbosity.quiet, suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow], deadline=None)
    @pytest.mark.property_test
    def test_form_submission_email_type_handling(self, page: Page, notification_page, notification_data):
        """Property test: EMAIL type notifications include subject field.
        
        **Validates: Requirements 2.2, 3.1**
        
        For any valid EMAIL notification data:
        1. Verify the form correctly handles EMAIL type selection
        2. Verify subject field becomes visible for EMAIL type
        3. Verify subject field value is included in API request
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            notification_data: Valid notification data from Hypothesis generator
        """
        # Skip if not EMAIL type
        if notification_data['type'] != 'EMAIL':
            return
        
        # List to capture intercepted requests
        intercepted_requests = []
        
        def handle_route(route):
            """Intercept and capture API requests."""
            if '/api/v1/notifications' in route.request.url:
                intercepted_requests.append({
                    'url': route.request.url,
                    'method': route.request.method,
                    'body': route.request.post_data_json
                })
            route.abort()
        
        # Navigate and set up interception
        notification_page.navigate()
        page.route('**/api/v1/notifications', handle_route)
        
        # Fill form with EMAIL data
        notification_page.fill_form(
            notification_data['type'],
            notification_data['recipient'],
            notification_data['message'],
            notification_data['subject']
        )
        
        # Verify subject field is visible for EMAIL
        assert notification_page.is_subject_visible(), \
            "Subject field should be visible for EMAIL notification type"
        
        # Submit the form
        notification_page.submit()
        
        # Verify request was sent
        assert len(intercepted_requests) > 0, \
            "Expected POST request to /api/v1/notifications"
        
        # Verify subject is in request body for EMAIL
        request_body = intercepted_requests[0]['body']
        assert 'subject' in request_body, \
            f"EMAIL request should include subject field. Got: {request_body}"
        assert request_body['subject'] == notification_data['subject'], \
            f"Subject field should match input. Expected: {notification_data['subject']}, Got: {request_body['subject']}"
    
    @given(notification_data=valid_notifications())
    @settings(max_examples=25, verbosity=Verbosity.quiet, suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow], deadline=None)
    @pytest.mark.property_test
    def test_form_submission_sms_type_no_subject(self, page: Page, notification_page, notification_data):
        """Property test: SMS type notifications do NOT include subject field.
        
        **Validates: Requirements 2.2, 3.1**
        
        For any valid SMS notification data:
        1. Verify the form correctly handles SMS type selection
        2. Verify subject field is hidden for SMS type
        3. Verify no subject field is included in API request
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            notification_data: Valid notification data from Hypothesis generator
        """
        # Skip if not SMS type
        if notification_data['type'] != 'SMS':
            return
        
        # List to capture intercepted requests
        intercepted_requests = []
        
        def handle_route(route):
            """Intercept and capture API requests."""
            if '/api/v1/notifications' in route.request.url:
                intercepted_requests.append({
                    'url': route.request.url,
                    'method': route.request.method,
                    'body': route.request.post_data_json
                })
            route.abort()
        
        # Navigate and set up interception
        notification_page.navigate()
        page.route('**/api/v1/notifications', handle_route)
        
        # Fill form with SMS data (no subject)
        notification_page.fill_form(
            notification_data['type'],
            notification_data['recipient'],
            notification_data['message']
        )
        
        # Verify subject field is NOT visible for SMS
        assert not notification_page.is_subject_visible(), \
            "Subject field should NOT be visible for SMS notification type"
        
        # Submit the form
        notification_page.submit()
        
        # Verify request was sent
        assert len(intercepted_requests) > 0, \
            "Expected POST request to /api/v1/notifications"
        
        # Verify subject is NOT in request body for SMS
        request_body = intercepted_requests[0]['body']
        assert 'subject' not in request_body, \
            f"SMS request should NOT include subject field. Got: {request_body}"
    
    @given(notification_data=valid_notifications())
    @settings(max_examples=25, verbosity=Verbosity.quiet, suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow], deadline=None)
    @pytest.mark.property_test
    def test_form_submission_whatsapp_type_no_subject(self, page: Page, notification_page, notification_data):
        """Property test: WHATSAPP type notifications do NOT include subject field.
        
        **Validates: Requirements 2.2, 3.1**
        
        For any valid WHATSAPP notification data:
        1. Verify the form correctly handles WHATSAPP type selection
        2. Verify subject field is hidden for WHATSAPP type
        3. Verify no subject field is included in API request
        
        Args:
            page: Playwright page fixture
            notification_page: NotificationPage Page Object Model fixture
            notification_data: Valid notification data from Hypothesis generator
        """
        # Skip if not WHATSAPP type
        if notification_data['type'] != 'WHATSAPP':
            return
        
        # List to capture intercepted requests
        intercepted_requests = []
        
        def handle_route(route):
            """Intercept and capture API requests."""
            if '/api/v1/notifications' in route.request.url:
                intercepted_requests.append({
                    'url': route.request.url,
                    'method': route.request.method,
                    'body': route.request.post_data_json
                })
            route.abort()
        
        # Navigate and set up interception
        notification_page.navigate()
        page.route('**/api/v1/notifications', handle_route)
        
        # Fill form with WHATSAPP data (no subject)
        notification_page.fill_form(
            notification_data['type'],
            notification_data['recipient'],
            notification_data['message']
        )
        
        # Verify subject field is NOT visible for WHATSAPP
        assert not notification_page.is_subject_visible(), \
            "Subject field should NOT be visible for WHATSAPP notification type"
        
        # Submit the form
        notification_page.submit()
        
        # Verify request was sent
        assert len(intercepted_requests) > 0, \
            "Expected POST request to /api/v1/notifications"
        
        # Verify subject is NOT in request body for WHATSAPP
        request_body = intercepted_requests[0]['body']
        assert 'subject' not in request_body, \
            f"WHATSAPP request should NOT include subject field. Got: {request_body}"
